#' Estimate Decision Tree Function
#'
#' This function estimates final payoffs from a decision tree object.
#' @param tree a decision tree/graph object generated by create_tree()
#' @param payoffs a list of cost/effect column names to use during estimation
#'
#' @return list with tree outcomes (pathprobabs, payoffs, weighted payoffs)
#'
#' @examples
#' results <- estimate_tree(tree, c("cost","effect"))
#'
#' @export

estimate_tree <- function(tree, payoffs = NULL)
{
  # get root and terminal nodes
  root_node      <- V(tree)[V(tree)$type == ROOT]
  terminal_nodes <- V(tree)[V(tree)$type == END]

  # get all possible paths from root to terminal
  pathways <- all_simple_paths(tree, from = root_node, to = terminal_nodes, mode = "all")

  #calculate path probability for every path in the tree
  weights       <- sapply(pathways, function(x) prod(E(tree, path = x)$probability))

  #create a matrix with nrows = # terminal nodes and ncols = # outcomes you want to measure
  pay           <- matrix(nrow = length(terminal_nodes), ncol = length(payoffs) )
  colnames(pay)  <- payoffs

  # iterate through the requested payoffs and include them in the estimation
  for (i in payoffs) {

    # standard expression to sum attributes (payoffs) for all paths in the tree
    expr <- paste("sapply(pathways, function(x) sum(E(tree, path = x)$", i, "))", sep = "")

    # apply standard expression to the tree to calculate the payoffs for every path
    pay[, i] <- eval(parse(text = expr))
  }

  #multiply path probabilities (vector) with path payoffs and return all results separately
  e.payoffs <- weights %*% pay
  return( list(weights = weights, pay = pay, payoffs = e.payoffs) )
}
